"""Per-sub credential storage for multi-user remote mode + sub-aware save.

Migrated to mcp_core.storage.per_plugin_store for trust model alignment.
Storage layout:
    Single-user: ~/.imagine-mcp/config.json
    Multi-user:  ~/.imagine-mcp/subs/<sub>/config.json

Replaces legacy mcp_core.storage.config_file (shared config.enc) which
caused multi-daemon path-drift contention.

Stdio mode pure-env policy (spec 2026-05-01-stdio-pure-http-multiuser §4.1):
    Stdio = env vars ONLY. PerPluginStore reads are gated behind ``_is_http()``
    so that a stdio process never silently picks up credentials from a config
    file written by a previous HTTP-mode session. ``_is_http`` mirrors the
    detection logic in ``imagine_mcp.__main__`` (``--http`` flag,
    ``MCP_TRANSPORT=http``, ``TRANSPORT_MODE=http``).
"""

from __future__ import annotations

import os
import sys

from mcp_core.storage.per_plugin_store import PerPluginStore

PLUGIN_NAME = "imagine"


def _is_http() -> bool:
    """Return True when the current process runs in HTTP mode.

    Mirrors ``imagine_mcp.__main__.main`` so PerPluginStore fallback reads
    only happen in HTTP mode. In stdio mode, credentials must come from
    env vars exclusively (per spec 2026-05-01 §4.1 + OQ3).
    """
    return (
        "--http" in sys.argv
        or os.environ.get("MCP_TRANSPORT") == "http"
        or os.environ.get("TRANSPORT_MODE") == "http"
    )


# ---------------------------------------------------------------------------
# Low-level per-sub helpers (preserve existing API surface for server.py)
# ---------------------------------------------------------------------------


def store_for_sub(sub: str, config: dict[str, str]) -> None:
    """Persist ``config`` for a specific JWT subject."""
    PerPluginStore(PLUGIN_NAME, sub).save(config)


def read_for_sub(sub: str) -> dict[str, str]:
    """Read the stored config for ``sub``; ``{}`` if not yet stored.

    Per-sub reads only make sense in HTTP multi-user mode -- the JWT subject
    is issued by mcp-core's local OAuth AS, which only runs under
    ``run_http_server``. Returns ``{}`` in stdio mode (no fallback).
    """
    if not _is_http():
        return {}
    return PerPluginStore(PLUGIN_NAME, sub).load() or {}


# ---------------------------------------------------------------------------
# Public helpers (used by relay_setup + server)
# ---------------------------------------------------------------------------


def load_credentials(sub: str | None = None) -> dict:
    """Load credentials for optional sub. Returns {} if not found.

    Stdio mode skips PerPluginStore entirely (env-only policy); HTTP mode
    reads the per-sub or single-user store as before.
    """
    if not _is_http():
        return {}
    return PerPluginStore(PLUGIN_NAME, sub).load() or {}


def clear_credentials(sub: str | None = None) -> None:
    """Remove stored credentials for optional sub."""
    PerPluginStore(PLUGIN_NAME, sub).clear()


def save_credentials(
    config: dict[str, str],
    context: dict[str, str] | None = None,
) -> dict | None:
    """Sub-aware credentials persistence. Wired into ``run_http_server``.

    Multi-user remote mode (``PUBLIC_URL`` set):
        Every authorize session has a fresh ``sub`` UUID generated by
        ``mcp_core.auth.local_oauth_app``. We require it and scope the
        config under ``~/.imagine-mcp/subs/<sub>/config.json`` -- never
        write to a shared store (would leak credentials across users).

    Single-user default mode:
        Persist under ``~/.imagine-mcp/config.json`` and apply env vars.
    """
    if os.environ.get("PUBLIC_URL"):
        sub = context.get("sub") if context else None
        if not sub:
            raise RuntimeError("multi-user mode: SubjectContext sub required")
        store_for_sub(sub, config)
        return None

    # Single-user path: persist via PerPluginStore + apply env vars.
    PerPluginStore(PLUGIN_NAME).save(config)
    from imagine_mcp.relay_setup import apply_config

    apply_config(config)
    return None
