"""Per-sub credential storage for multi-user remote mode + sub-aware save.

In single-user (default) mode, credentials are persisted via mcp-core's
encrypted ``config.enc`` (see ``imagine_mcp.relay_setup.save_credentials``).

In multi-user remote mode (``PUBLIC_URL`` env set, server bound to
``0.0.0.0:8080`` via ``run_http``), every authorize-session carries a fresh
per-user JWT ``sub`` produced by ``mcp_core.auth.local_oauth_app``; we store
that user's LLM provider keys under ``IMAGINE_DATA_DIR/subs/<sub>/config.json``
so the API keys of one user are never returned to another user's tool calls.
"""

from __future__ import annotations

import json
import os
from pathlib import Path


def _sub_data_dir(sub: str) -> Path:
    base = Path(os.environ.get("IMAGINE_DATA_DIR", str(Path.home() / ".imagine-mcp")))
    d = base / "subs" / sub
    d.mkdir(parents=True, exist_ok=True)
    return d


def store_for_sub(sub: str, config: dict[str, str]) -> None:
    """Persist ``config`` for a specific JWT subject."""
    (_sub_data_dir(sub) / "config.json").write_text(json.dumps(config))


def read_for_sub(sub: str) -> dict[str, str]:
    """Read the stored config for ``sub``; ``{}`` if not yet stored."""
    p = _sub_data_dir(sub) / "config.json"
    return json.loads(p.read_text()) if p.exists() else {}


def save_credentials(
    config: dict[str, str],
    context: dict[str, str] | None = None,
) -> dict | None:
    """Sub-aware credentials persistence. Wired into ``run_local_server``.

    Multi-user remote mode (``PUBLIC_URL`` set):
        Every authorize session has a fresh ``sub`` UUID generated by
        ``mcp_core.auth.local_oauth_app``. We require it and scope the
        config under ``subs/<sub>/config.json`` -- never write to a shared
        ``config.enc`` (would leak credentials across users).

    Single-user default mode:
        Delegate to ``relay_setup.save_credentials`` which writes to the
        existing ``config.enc`` and applies env vars (back-compat).
    """
    if os.environ.get("PUBLIC_URL"):
        sub = context.get("sub") if context else None
        if not sub:
            raise RuntimeError("multi-user mode: SubjectContext sub required")
        store_for_sub(sub, config)
        return None

    # Single-user path: delegate to existing relay_setup logic.
    from imagine_mcp.relay_setup import save_credentials as _legacy_save

    return _legacy_save(config, context)
