"""Per-sub credential storage for multi-user remote mode + sub-aware save.

Migrated to mcp_core.storage.per_plugin_store for trust model alignment.
Storage layout:
    Single-user: ~/.imagine-mcp/config.json
    Multi-user:  ~/.imagine-mcp/subs/<sub>/config.json

Replaces legacy mcp_core.storage.config_file (shared config.enc) which
caused multi-daemon path-drift contention.
"""

from __future__ import annotations

import os
from typing import Optional

from mcp_core.storage.per_plugin_store import PerPluginStore

PLUGIN_NAME = "imagine"


# ---------------------------------------------------------------------------
# Low-level per-sub helpers (preserve existing API surface for server.py)
# ---------------------------------------------------------------------------


def store_for_sub(sub: str, config: dict[str, str]) -> None:
    """Persist ``config`` for a specific JWT subject."""
    PerPluginStore(PLUGIN_NAME, sub).save(config)


def read_for_sub(sub: str) -> dict[str, str]:
    """Read the stored config for ``sub``; ``{}`` if not yet stored."""
    return PerPluginStore(PLUGIN_NAME, sub).load() or {}


# ---------------------------------------------------------------------------
# Public helpers (used by relay_setup + server)
# ---------------------------------------------------------------------------


def load_credentials(sub: Optional[str] = None) -> dict:
    """Load credentials for optional sub. Returns {} if not found."""
    return PerPluginStore(PLUGIN_NAME, sub).load() or {}


def clear_credentials(sub: Optional[str] = None) -> None:
    """Remove stored credentials for optional sub."""
    PerPluginStore(PLUGIN_NAME, sub).clear()


def save_credentials(
    config: dict[str, str],
    context: Optional[dict[str, str]] = None,
) -> Optional[dict]:
    """Sub-aware credentials persistence. Wired into ``run_local_server``.

    Multi-user remote mode (``PUBLIC_URL`` set):
        Every authorize session has a fresh ``sub`` UUID generated by
        ``mcp_core.auth.local_oauth_app``. We require it and scope the
        config under ``~/.imagine-mcp/subs/<sub>/config.json`` -- never
        write to a shared store (would leak credentials across users).

    Single-user default mode:
        Persist under ``~/.imagine-mcp/config.json`` and apply env vars.
    """
    if os.environ.get("PUBLIC_URL"):
        sub = context.get("sub") if context else None
        if not sub:
            raise RuntimeError("multi-user mode: SubjectContext sub required")
        store_for_sub(sub, config)
        return None

    # Single-user path: persist via PerPluginStore + apply env vars.
    PerPluginStore(PLUGIN_NAME).save(config)
    from imagine_mcp.relay_setup import apply_config

    apply_config(config)
    return None
