"""Render docs/models.md from src/imagine_mcp/models.py MODELS list.

Called by:
  - `mise run refresh-ranks` (chained after fetch_leaderboards.py)
  - `.pre-commit-config.yaml` hook (drift detection with --check)
  - GH Action refresh-ranks.yml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from imagine_mcp.models import MODELS, UNSUPPORTED, ModelEntry

_HEADER = """<!-- AUTO-GENERATED by scripts/gen_models_table.py from src/imagine_mcp/models.py -->
<!-- Do not edit manually. Run `mise run refresh-ranks` or `python scripts/gen_models_table.py`. -->

# Model ID Mapping

Sorted by (action, media, tier, quality_rank ASC). Updated from Artificial Analysis + LMArena leaderboards.

"""


def _group_key(e: ModelEntry) -> tuple[str, str, str]:
    return (e.action, e.media, e.tier)


def render_markdown(models: list[ModelEntry]) -> str:
    sorted_models = sorted(
        models,
        key=lambda e: (
            e.action,
            e.media,
            e.tier,
            e.quality_rank if e.quality_rank is not None else 10**9,
            e.provider,
        ),
    )
    out: list[str] = [_HEADER]
    current_group: tuple[str, str, str] | None = None
    for e in sorted_models:
        g = _group_key(e)
        if g != current_group:
            out.append(f"## {e.action} / {e.media} / {e.tier}\n")
            out.append("| Rank | Provider | Model ID | Cost | Last verified | Notes |")
            out.append("|:----:|----------|----------|:----:|:-------------:|-------|")
            current_group = g
        rank = str(e.quality_rank) if e.quality_rank is not None else "—"
        model = "**ERROR**" if e.model_id is UNSUPPORTED else f"`{e.model_id}`"
        notes = e.notes.replace("|", r"\|") if e.notes else ""
        out.append(
            f"| {rank} | {e.provider} | {model} | {e.cost_tier} | "
            f"{e.last_verified.isoformat()} | {notes} |"
        )
    out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if docs/models.md drifts from models.py",
    )
    args = parser.parse_args(argv)

    repo_root = Path(__file__).resolve().parent.parent
    target = repo_root / "docs" / "models.md"
    rendered = render_markdown(MODELS)

    if args.check:
        if not target.exists():
            print(
                "docs/models.md does not exist; run without --check to create",
                file=sys.stderr,
            )
            return 1
        if target.read_text(encoding="utf-8") != rendered:
            print(
                "docs/models.md drift from src/imagine_mcp/models.py",
                file=sys.stderr,
            )
            return 1
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered, encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
